version: "3"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "gigachat"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./postgresql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gigachat"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  auth:
    build: auth/
    environment:
      POSTGRES_URL: "postgres://admin:admin@postgres:5432/gigachat"
      JWT_SECRET: "gigachat"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3001"

  comments:
    build: comments/
    environment:
      POSTGRES_URL: "postgres://admin:admin@postgres:5432/gigachat"
      JWT_SECRET: "gigachat"
      AUTH_URL: "http://auth:3001/gigachat/auth/api/v1/auth"
    depends_on:
      postgres:
        condition: service_healthy
      auth: {}
    ports:
      - "3002:3002"

  publish:
    build: publish/
    environment:
      POSTGRES_URL: "postgres://admin:admin@postgres:5432/gigachat"
      JWT_SECRET: "gigachat"
      AUTH_URL: "http://auth:3001/gigachat/auth/api/v1/auth"
    depends_on:
      postgres:
        condition: service_healthy
      auth: {}
      comments: {}
    ports:
      - "3003:3003"

  front:
    build: front/gigachat
    ports:
      - "3000:3000"
